resilience4j.circuitbreaker:
  instances:
    userServices:
      register-health-indicator: true
      wait-duration-in-open-state: 10s
      failure-rate-threshold: 10
      slow-call-rate-threshold: 10
      slow-call-duration-threshold: 1s
      minimum-number-of-calls: 5
      automatic-transition-from-open-to-half-open-enabled: true

resilience4j.retry:
  instances:
    userServicesRetry:
      max-attempts: 3
      wait-duration: 1s
  metrics:
    enabled: true

resilience4j.ratelimiter:
    metrics:
      enabled: true
    instances:
      userServicesRateLimiter:
        register-health-indicator: true
        limit-for-period: 5
        limit-refresh-period: 60s
        timeout-duration: 0s
        allow-health-indicator-to-fail: true
        subscribe-for-events: true
        event-consumer-buffer-size: 50

resilience4j:
  bulkhead:
    instances:
      userServicesBulkhead:
        max-concurrent-calls: 3
        max-wait-duration: 1s
    metrics:
      enabled: true